- name: Create an ec2 instance
  ec2:
    key_name: "{{ keypair }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    group: SG1  # security group name of your existing instance
    instance_type: "{{ instance_type}}"
    image: "{{ ami }}"
    user_data: |
               #!/bin/sh
               sudo yum install python2 -y
               sudo ln -s /usr/bin/python2 /usr/bin/python
    wait: true
    region: "{{ region }}"
    count: 1  # default
    count_tag:
      Name: "Demo"
    instance_tags:
      Name: "Demo"
    vpc_subnet_id: "subnet-286e1552" # subnet id of existing aws instance so that in thatsame subnet this new instance will create.
    assign_public_ip: yes
  register: ec2

- name: Adding delay
  shell: sleep 60
    
- debug:
    msg: "{{ item['private_ip'] }}"
  with_items: "{{ ec2.instances }}"

- name: Add all web instance IPs to host group
  add_host: 
    hostname: "{{ item.private_ip }}"
    groupname: webservers
    ansible_user: ec2-user 
  with_items: '{{ ec2.instances }}'

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: '{{ ec2.instances }}'
       

